import { AssetsUtils } from "@/utils/AssetsUtils";

export const products = [
  {
    id: 1,
    title: "B/W Full Body Outfit",
    description: "Jumper set for Women",
    price: "$89",
    img: AssetsUtils.images.product.productImg1,
  },
  {
    id: 2,
    title: "Black Semi-Formal Coat",
    description: "Coat for Women",
    price: "$159",
    img: AssetsUtils.images.product.productImg2,
  },
  {
    id: 3,
    title: "Ocean Blue Fullsleeved",
    description: "Denim Jacket for Men",
    price: "$79",
    img: AssetsUtils.images.product.productImg3,
  },
  {
    id: 4,
    title: "Red Buttoned Sweater",
    description: "Sweater for Men",
    price: "$89",
    img: AssetsUtils.images.product.productImg4,
  },
  {
    id: 5,
    title: "B/W Full Body Outfit",
    description: "Jumper set for Women",
    price: "$89",
    img: AssetsUtils.images.product.productImg5,
  },
  {
    id: 6,
    title: "Black Semi-Formal Coat",
    description: "Coat for Women",
    price: "$159",
    img: AssetsUtils.images.product.productImg6,
  },
  {
    id: 7,
    title: "Ocean Blue Fullsleeved",
    description: "Denim Jacket for Men",
    price: "$79",
    img: AssetsUtils.images.product.productImg7,
  },
  {
    id: 8,
    title: "Red Buttoned Sweater",
    description: "Sweater for Men",
    price: "$89",
    img: AssetsUtils.images.product.productImg8,
  },
  {
    id: 9,
    title: "B/W Full Body Outfit",
    description: "Jumper set for Women",
    price: "$89",
    img: AssetsUtils.images.product.shoe1,
  },
  {
    id: 10,
    title: "Black Semi-Formal Coat",
    description: "Coat for Women",
    price: "$159",
    img: AssetsUtils.images.product.shoe2,
  },
  {
    id: 11,
    title: "Ocean Blue Fullsleeved",
    description: "Denim Jacket for Men",
    price: "$79",
    img: AssetsUtils.images.product.shoe3,
  },
  {
    id: 12,
    title: "Red Buttoned Sweater",
    description: "Sweater for Men",
    price: "$89",
    img: AssetsUtils.images.product.shoe4,
  },
  {
    id: 13,
    title: "B/W Full Body Outfit",
    description: "Jumper set for Women",
    price: "$89",
    img: AssetsUtils.images.product.shirt1,
  },
  {
    id: 14,
    title: "Black Semi-Formal Coat",
    description: "Coat for Women",
    price: "$159",
    img: AssetsUtils.images.product.shirt2,
  },
  {
    id: 15,
    title: "Ocean Blue Fullsleeved",
    description: "Denim Jacket for Men",
    price: "$79",
    img: AssetsUtils.images.product.shirt3,
  },
  {
    id: 16,
    title: "Red Buttoned Sweater",
    description: "Sweater for Men",
    price: "$89",
    img: AssetsUtils.images.product.shoe5,
  },
  {
    id: 17,
    title: "B/W Full Body Outfit",
    description: "Jumper set for Women",
    price: "$89",
    img: AssetsUtils.images.product.bag1,
  },
  {
    id: 18,
    title: "Black Semi-Formal Coat",
    description: "Coat for Women",
    price: "$159",
    img: AssetsUtils.images.product.bag2,
  },
  {
    id: 19,
    title: "Ocean Blue Fullsleeved",
    description: "Denim Jacket for Men",
    price: "$79",
    img: AssetsUtils.images.product.bag3,
  },
  {
    id: 20,
    title: "Red Buttoned Sweater",
    description: "Sweater for Men",
    price: "$89",
    img: AssetsUtils.images.product.bag4,
  },
];

export const popular_products = [
  {
    id: 1,
    title: "B/W Full Body Outfit",
    description: "Jumper set for Women",
    price: "$89",
    img: AssetsUtils.images.product.ladyBlackShort,
  },
  {
    id: 2,
    title: "Black Semi-Formal Coat",
    description: "Coat for Women",
    price: "$159",
    img: AssetsUtils.images.product.ladyGown,
  },
  {
    id: 3,
    title: "Ocean Blue Fullsleeved",
    description: "Denim Jacket for Men",
    price: "$79",
    img: AssetsUtils.images.product.ladyJeanShort,
  },
  {
    id: 4,
    title: "Red Buttoned Sweater",
    description: "Sweater for Men",
    price: "$89",
    img: AssetsUtils.images.product.ladyJean,
  },
];

export const more_from_brand = [
  {
    id: 1,
    title: "B/W Full Body Outfit",
    description: "Jumper set for Women",
    price: "$89",
    img: AssetsUtils.images.product.ladySweaters,
  },
  {
    id: 2,
    title: "Black Semi-Formal Coat",
    description: "Coat for Women",
    price: "$159",
    img: AssetsUtils.images.product.bag1,
  },
  {
    id: 3,
    title: "Ocean Blue Fullsleeved",
    description: "Denim Jacket for Men",
    price: "$79",
    img: AssetsUtils.images.product.pinkSweaters,
  },
  {
    id: 4,
    title: "Red Buttoned Sweater",
    description: "Sweater for Men",
    price: "$89",
    img: AssetsUtils.images.product.ashSweaters,
  },
];
